translate :: String -> String
translate xs = concat $ takeWhile (/= "Stop") $ map amino $ triples xs

triples :: [a] -> [[a]]
triples [] = []
triples xs = y:(triples ys)
    where (y, ys) = splitAt 3 xs

-- Translate Codon to Amino Acid
amino :: String -> String 
amino "UUU" = "F"
amino "CUU" = "L"
amino "AUU" = "I"
amino "GUU" = "V"
amino "UUC" = "F"
amino "CUC" = "L"
amino "AUC" = "I"
amino "GUC" = "V"
amino "UUA" = "L"
amino "CUA" = "L"
amino "AUA" = "I"
amino "GUA" = "V"
amino "UUG" = "L"
amino "CUG" = "L"
amino "AUG" = "M"
amino "GUG" = "V"
amino "UCU" = "S"
amino "CCU" = "P"
amino "ACU" = "T"
amino "GCU" = "A"
amino "UCC" = "S"
amino "CCC" = "P"
amino "ACC" = "T"
amino "GCC" = "A"
amino "UCA" = "S"
amino "CCA" = "P"
amino "ACA" = "T"
amino "GCA" = "A"
amino "UCG" = "S"
amino "CCG" = "P"
amino "ACG" = "T"
amino "GCG" = "A"
amino "UAU" = "Y"
amino "CAU" = "H"
amino "AAU" = "N"
amino "GAU" = "D"
amino "UAC" = "Y"
amino "CAC" = "H"
amino "AAC" = "N"
amino "GAC" = "D"
amino "UAA" = "Stop"
amino "CAA" = "Q"
amino "AAA" = "K"
amino "GAA" = "E"
amino "UAG" = "Stop"
amino "CAG" = "Q"
amino "AAG" = "K"
amino "GAG" = "E"
amino "UGU" = "C"
amino "CGU" = "R"
amino "AGU" = "S"
amino "GGU" = "G"
amino "UGC" = "C"
amino "CGC" = "R"
amino "AGC" = "S"
amino "GGC" = "G"
amino "UGA" = "Stop"
amino "CGA" = "R"
amino "AGA" = "R"
amino "GGA" = "G"
amino "UGG" = "W"
amino "CGG" = "R"
amino "AGG" = "R"
amino "GGG" = "G"
